DROP TABLE INT_CTRL_TASK_CATALOG ;
CREATE TABLE INT_CTRL_TASK_CATALOG (
    ID NUMBER NOT NULL ,
    FORMAL_NAME VARCHAR2(1024) , 
    JS_FUNCTION_NAME VARCHAR2(1024) , 
    DISPLAY_NAME VARCHAR2(1024) , 
    CHART_TYPE VARCHAR2(1024) , 
    STATUS VARCHAR2(32) , 
    STORED_PROCEDURED_NAME VARCHAR2(1024) , 
    OPTION_FLAG VARCHAR2(1024) , 
    LAST_UPDATE_BY VARCHAR2(1024) ,
    LAST_UPDATE_DATE DATE , 
    Position_Order NUMBER , 
    CONSTRAINT INT_CTRL_TASK_CATALOG_PK PRIMARY KEY ( ID ) ENABLE 
);
commit;
