DROP TABLE INT_CTRL_MMBERSHIP;
CREATE TABLE INT_CTRL_MMBERSHIP (
    U_ID VARCHAR2(1024) NOT NULL ,
    FORMAL_NAME VARCHAR2(1024) , 
    IMAGE_NAME bfile , 
    ROL_FUNCTION_NAME VARCHAR2(1024) , 
    DISPLAY_NAME VARCHAR2(1024) , 
    STATUS VARCHAR2(32) , 
    OPTION_FLAG VARCHAR2(1024) , 
    LAST_UPDATE_BY VARCHAR2(1024) ,
    LAST_UPDATE_DATE DATE ,
    CONSTRAINT INT_CTRL_MMBERSHIP_PK PRIMARY KEY ( U_ID ) ENABLE 
);
commit;