DROP TABLE INT_CTRL_Assigned_ACT ;
CREATE TABLE INT_CTRL_Assigned_ACT (
    AssAct_Id VARCHAR2(1024) NOT NULL ,
    U_ID VARCHAR2(1024) NOT NULL ,
    P_ID VARCHAR2(1024) NOT NULL ,
    prefered_date date ,
    STATUS VARCHAR2(32) , 
    OPTION_FLAG VARCHAR2(1024) , 
    LAST_UPDATE_BY VARCHAR2(1024) ,
    LAST_UPDATE_DATE DATE 
);
commit;
