DROP TABLE INT_CTRL_Task_Gallery;
CREATE TABLE INT_CTRL_Task_Gallery (
    T_ID NUMBER NOT NULL ,
    FORMAL_NAME VARCHAR2(1024) , 
    FUNCTION_NAME VARCHAR2(1024) , 
    DISPLAY_NAME VARCHAR2(1024) , 
    STATUS VARCHAR2(32) , 
    OPTION_FLAG VARCHAR2(1024) , 
    LAST_UPDATE_BY VARCHAR2(1024) ,
    LAST_UPDATE_DATE DATE ,
    CONSTRAINT INT_CTRL_Task_Gallery_PK PRIMARY KEY ( T_ID ) ENABLE 
);
commit;