DROP TABLE INT_CTRL_Running_Process ;
CREATE TABLE INT_CTRL_Running_Process (
    U_ID NUMBER NOT NULL ,
    Any_Comments VARCHAR2(1024) , 
    JS_FUNCTION_NAME VARCHAR2(1024) , 
    OPERATION_TYPE VARCHAR2(1024) , 
    STATUS VARCHAR2(32) , 
    STORED_PROCEDURED_NAME VARCHAR2(1024) , 
    Severity_Level VARCHAR2(1024) , 
    OPTION_FLAG VARCHAR2(1024) , 
    Start_DATE DATE ,
    END_DATE DATE ,
    LAST_UPDATE_BY VARCHAR2(1024) ,
    LAST_UPDATE_DATE DATE 
);
commit;
